# Generated by Django 3.2.8 on 2021-10-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informasi_Publik',
            fields=[
                ('id_informasi', models.IntegerField(primary_key=True, serialize=False)),
                ('judul', models.CharField(blank=True, max_length=200, null=True)),
                ('isi', models.CharField(blank=True, max_length=500, null=True)),
                ('visibilitas', models.IntegerField(choices=[(1, 'Hanya Staf'), (2, 'Publik')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
