# Generated by Django 3.2.8 on 2021-10-15 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pendaftaran_wisuda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gelar_Vokasi_Belakang',
            fields=[
                ('id_gelar_belakang', models.AutoField(primary_key=True, serialize=False)),
                ('gelar_belakang', models.CharField(blank=True, max_length=200, null=True)),
                ('gelar_akademik', models.CharField(blank=True, max_length=200, null=True)),
                ('lulusan', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gelar_Vokasi_Depan',
            fields=[
                ('id_gelar_depan', models.AutoField(primary_key=True, serialize=False)),
                ('gelar_depan', models.CharField(blank=True, max_length=200, null=True)),
                ('gelar_akademik', models.CharField(blank=True, max_length=200, null=True)),
                ('lulusan', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal_Wisuda',
            fields=[
                ('id_jadwal_wisuda', models.AutoField(primary_key=True, serialize=False)),
                ('gelombang', models.CharField(choices=[('Kedua', 'Kedua'), ('Pertama', 'Pertama')], default='Pertama', max_length=150)),
                ('tanggal_wisuda', models.DateField(blank=True, null=True)),
                ('waktu_wisuda', models.TimeField(blank=True, null=True)),
                ('lokasi_wisuda', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id_mahasiswa', models.AutoField(primary_key=True, serialize=False)),
                ('nama_mahasiswa', models.CharField(blank=True, max_length=200, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('laki-laki', 'Laki-laki'), ('perempuan', 'Perempuan')], max_length=150, null=True)),
                ('nim', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat', models.CharField(blank=True, max_length=300, null=True)),
                ('status_keaktifan', models.CharField(choices=[('Non-Aktif', 'Non-Aktif'), ('Aktif', 'Aktif')], default='Aktif', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program_Studi',
            fields=[
                ('id_program_studi', models.AutoField(primary_key=True, serialize=False)),
                ('nama_program_studi', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='informasi_publik',
            name='visibilitas',
            field=models.CharField(choices=[('Hanya Staf', 'Hanya Staf'), ('Publik', 'Publik')], default='Hanya Staf', max_length=150),
        ),
        migrations.CreateModel(
            name='Pendaftaran_Wisuda',
            fields=[
                ('id_pendaftaran_wisuda', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_pendaftaran', models.CharField(choices=[('Pendaftaran Wisuda', 'Pendaftaran Wisuda')], default='Pendaftaran Wisuda', max_length=150)),
                ('ukuran_toga', models.CharField(choices=[('XL', 'XL'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XXL', 'XL')], default='L', max_length=150)),
                ('status_approval', models.CharField(choices=[('Tidak Disetujui', 'Tidak Disetujui'), ('Disetujui', 'Disetujui'), ('Belum Disetujui', 'Belum Disetujui')], default='Belum Disetujui', max_length=150)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_mahasiswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_wisuda.mahasiswa')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='program_studi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_wisuda.program_studi'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Akademik',
            fields=[
                ('id_akademik', models.AutoField(primary_key=True, serialize=False)),
                ('nama_akademik', models.CharField(max_length=200, null=True)),
                ('tempat_lahir', models.CharField(max_length=200, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('Perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki')], max_length=150, null=True)),
                ('no_ktp', models.CharField(blank=True, max_length=100, null=True)),
                ('status_keaktifan', models.CharField(choices=[('Non-Aktif', 'Non-Aktif'), ('Aktif', 'Aktif')], default='Aktif', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gelar_belakang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_wisuda.gelar_vokasi_belakang')),
                ('gelar_depan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_wisuda.gelar_vokasi_depan')),
                ('prodi_yang_diampu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_wisuda.program_studi')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
