# Generated by Django 3.2.8 on 2021-10-15 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_wisuda', '0002_auto_20211015_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasi_publik',
            name='visibilitas',
            field=models.CharField(choices=[('Publik', 'Publik'), ('Hanya Staf', 'Hanya Staf')], default='Hanya Staf', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('perempuan', 'Perempuan'), ('laki-laki', 'Laki-laki')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='id_mahasiswa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_wisuda.mahasiswa'),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('XXL', 'XL'), ('M', 'M'), ('L', 'L'), ('S', 'S'), ('XL', 'XL')], default='L', max_length=150),
        ),
    ]
