# Generated by Django 3.2.8 on 2021-10-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_wisuda', '0003_auto_20211015_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akademik',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='informasi_publik',
            name='visibilitas',
            field=models.CharField(choices=[('Hanya Staf', 'Hanya Staf'), ('Publik', 'Publik')], default='Hanya Staf', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('laki-laki', 'Laki-laki'), ('perempuan', 'Perempuan')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='status_approval',
            field=models.CharField(choices=[('Tidak Disetujui', 'Tidak Disetujui'), ('Belum Disetujui', 'Belum Disetujui'), ('Disetujui', 'Disetujui')], default='Belum Disetujui', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('XL', 'XL'), ('XXL', 'XXL'), ('M', 'M'), ('L', 'L'), ('S', 'S')], default='L', max_length=150),
        ),
    ]
