# Generated by Django 3.2.8 on 2021-10-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_wisuda', '0007_auto_20211016_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran_wisuda',
            name='user',
        ),
        migrations.AlterField(
            model_name='akademik',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='status_keaktifan',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Non-Aktif', 'Non-Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='jadwal_wisuda',
            name='gelombang',
            field=models.CharField(choices=[('Kedua', 'Kedua'), ('Pertama', 'Pertama')], default='Pertama', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='status_keaktifan',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Non-Aktif', 'Non-Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='status_approval',
            field=models.CharField(choices=[('Belum Disetujui', 'Belum Disetujui'), ('Tidak Disetujui', 'Tidak Disetujui'), ('Disetujui', 'Disetujui')], default='Belum Disetujui', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('XXL', 'XXL'), ('M', 'M'), ('XL', 'XL'), ('S', 'S'), ('L', 'L')], default='L', max_length=150),
        ),
    ]
