# Generated by Django 3.2.8 on 2021-10-16 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pendaftaran_wisuda', '0009_auto_20211016_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akademik',
            name='status_keaktifan',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Non-Aktif', 'Non-Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='informasi_publik',
            name='visibilitas',
            field=models.CharField(choices=[('Hanya Staf', 'Hanya Staf'), ('Publik', 'Publik')], default='Hanya Staf', max_length=150),
        ),
        migrations.AlterField(
            model_name='jadwal_wisuda',
            name='gelombang',
            field=models.CharField(choices=[('Kedua', 'Kedua'), ('Pertama', 'Pertama')], default='Pertama', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='status_keaktifan',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Non-Aktif', 'Non-Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mahasiswa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='id_mahasiswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pendaftaran_Wisuda', to='pendaftaran_wisuda.mahasiswa'),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('S', 'S'), ('L', 'L'), ('M', 'M'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=150),
        ),
    ]
