# Generated by Django 3.2.8 on 2021-10-16 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pendaftaran_wisuda', '0010_auto_20211016_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal_wisuda',
            name='gelombang',
            field=models.CharField(choices=[('Pertama', 'Pertama'), ('Kedua', 'Kedua')], default='Pertama', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='status_approval',
            field=models.CharField(choices=[('Disetujui', 'Disetujui'), ('Belum Disetujui', 'Belum Disetujui'), ('Tidak Disetujui', 'Tidak Disetujui')], default='Belum Disetujui', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('XXL', 'XXL'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XL', 'XL')], default='L', max_length=150),
        ),
    ]
