# Generated by Django 3.2.8 on 2021-10-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_wisuda', '0012_auto_20211017_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_studi',
            name='id_fakultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_wisuda.fakultas'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='status_keaktifan',
            field=models.CharField(choices=[('Non-Aktif', 'Non-Aktif'), ('Aktif', 'Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='informasi_publik',
            name='visibilitas',
            field=models.CharField(choices=[('Hanya Staf', 'Hanya Staf'), ('Publik', 'Publik')], default='Hanya Staf', max_length=150),
        ),
        migrations.AlterField(
            model_name='jadwal_wisuda',
            name='gelombang',
            field=models.CharField(choices=[('Kedua', 'Kedua'), ('Pertama', 'Pertama')], default='Pertama', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='status_keaktifan',
            field=models.CharField(choices=[('Non-Aktif', 'Non-Aktif'), ('Aktif', 'Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('L', 'L'), ('S', 'S'), ('XL', 'XL'), ('XXL', 'XXL'), ('M', 'M')], default='L', max_length=150),
        ),
    ]
