# Generated by Django 3.2.8 on 2021-10-18 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_wisuda', '0013_auto_20211017_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran_wisuda',
            name='id_jadwal_wisuda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_wisuda.jadwal_wisuda'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='informasi_publik',
            name='isi',
            field=models.TextField(blank=True, default='...', null=True),
        ),
        migrations.AlterField(
            model_name='informasi_publik',
            name='visibilitas',
            field=models.CharField(choices=[('Publik', 'Publik'), ('Hanya Staf', 'Hanya Staf')], default='Hanya Staf', max_length=150),
        ),
        migrations.AlterField(
            model_name='jadwal_wisuda',
            name='gelombang',
            field=models.CharField(choices=[('Pertama', 'Pertama'), ('Kedua', 'Kedua')], default='Pertama', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='status_approval',
            field=models.CharField(choices=[('Tidak Disetujui', 'Tidak Disetujui'), ('Belum Disetujui', 'Belum Disetujui'), ('Disetujui', 'Disetujui')], default='Belum Disetujui', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('M', 'M'), ('XXL', 'XXL'), ('L', 'L'), ('S', 'S'), ('XL', 'XL')], default='L', max_length=150),
        ),
    ]
