# Generated by Django 3.2.8 on 2021-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_wisuda', '0014_auto_20211018_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='kelas',
            field=models.CharField(choices=[('B', 'B'), ('A', 'A')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='informasi_publik',
            name='visibilitas',
            field=models.CharField(choices=[('Hanya Staf', 'Hanya Staf'), ('Publik', 'Publik')], default='Hanya Staf', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('perempuan', 'Perempuan')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='status_approval',
            field=models.CharField(choices=[('Belum Disetujui', 'Belum Disetujui'), ('Disetujui', 'Disetujui'), ('Tidak Disetujui', 'Tidak Disetujui')], default='Belum Disetujui', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('M', 'M'), ('XXL', 'XXL'), ('S', 'S'), ('L', 'L'), ('XL', 'XL')], default='L', max_length=150),
        ),
    ]
