# Generated by Django 3.2.8 on 2021-10-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_wisuda', '0015_auto_20211018_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal_wisuda',
            name='id_mahasiswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_wisuda.mahasiswa'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='informasi_publik',
            name='visibilitas',
            field=models.CharField(choices=[('Publik', 'Publik'), ('Hanya Staf', 'Hanya Staf')], default='Hanya Staf', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='status_approval',
            field=models.CharField(choices=[('Tidak Disetujui', 'Tidak Disetujui'), ('Belum Disetujui', 'Belum Disetujui'), ('Disetujui', 'Disetujui')], default='Belum Disetujui', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('XXL', 'XXL'), ('XL', 'XL'), ('S', 'S'), ('L', 'L'), ('M', 'M')], default='L', max_length=150),
        ),
    ]
