# Generated by Django 3.2.8 on 2021-10-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_wisuda', '0019_auto_20211020_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal_wisuda',
            name='id_mahasiswa',
        ),
        migrations.AlterField(
            model_name='akademik',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='status_keaktifan',
            field=models.CharField(choices=[('Non-Aktif', 'Non-Aktif'), ('Aktif', 'Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='jadwal_wisuda',
            name='pelaksanaan',
            field=models.CharField(choices=[('Geladi Bersih', 'Geladi Bersih'), ('Utama', 'Utama')], default='Geladi Bersih', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='status_keaktifan',
            field=models.CharField(choices=[('Non-Aktif', 'Non-Aktif'), ('Aktif', 'Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='status_approval',
            field=models.CharField(choices=[('Disetujui', 'Disetujui'), ('Tidak Disetujui', 'Tidak Disetujui'), ('Belum Disetujui', 'Belum Disetujui')], default='Belum Disetujui', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('L', 'L'), ('XXL', 'XXL'), ('XL', 'XL'), ('S', 'S'), ('M', 'M')], default='L', max_length=150),
        ),
    ]
