# Generated by Django 3.2.8 on 2021-10-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_wisuda', '0021_auto_20211020_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='fakultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_wisuda.fakultas'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='status_keaktifan',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Non-Aktif', 'Non-Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='informasi_publik',
            name='visibilitas',
            field=models.CharField(choices=[('Publik', 'Publik'), ('Hanya Staf', 'Hanya Staf')], default='Hanya Staf', max_length=150),
        ),
        migrations.AlterField(
            model_name='jadwal_wisuda',
            name='pelaksanaan',
            field=models.CharField(choices=[('Utama', 'Utama'), ('Geladi Bersih', 'Geladi Bersih')], default='Geladi Bersih', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='kelas',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='status_keaktifan',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Non-Aktif', 'Non-Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='status_approval',
            field=models.CharField(choices=[('Tidak Disetujui', 'Tidak Disetujui'), ('Disetujui', 'Disetujui'), ('Belum Disetujui', 'Belum Disetujui')], default='Belum Disetujui', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('L', 'L'), ('XXL', 'XXL'), ('XL', 'XL'), ('M', 'M'), ('S', 'S')], default='L', max_length=150),
        ),
    ]
