# Generated by Django 3.2.8 on 2021-10-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_wisuda', '0022_auto_20211021_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal_wisuda',
            name='id_mahasiswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_wisuda.mahasiswa'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='status_keaktifan',
            field=models.CharField(choices=[('Non-Aktif', 'Non-Aktif'), ('Aktif', 'Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='jadwal_wisuda',
            name='pelaksanaan',
            field=models.CharField(choices=[('Geladi Bersih', 'Geladi Bersih'), ('Utama', 'Utama')], default='Geladi Bersih', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('perempuan', 'Perempuan')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='status_keaktifan',
            field=models.CharField(choices=[('Non-Aktif', 'Non-Aktif'), ('Aktif', 'Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='status_approval',
            field=models.CharField(choices=[('Tidak Disetujui', 'Tidak Disetujui'), ('Belum Disetujui', 'Belum Disetujui'), ('Disetujui', 'Disetujui')], default='Belum Disetujui', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('S', 'S'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=150),
        ),
    ]
