# Generated by Django 3.2.8 on 2021-10-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_wisuda', '0023_auto_20211023_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal_wisuda',
            name='id_mahasiswa',
        ),
        migrations.AlterField(
            model_name='akademik',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='status_keaktifan',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Non-Aktif', 'Non-Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='informasi_publik',
            name='visibilitas',
            field=models.CharField(choices=[('Hanya Staf', 'Hanya Staf'), ('Publik', 'Publik')], default='Hanya Staf', max_length=150),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='kelas',
            field=models.CharField(choices=[('B', 'B'), ('A', 'A')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='status_keaktifan',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Non-Aktif', 'Non-Aktif')], default='Aktif', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='status_approval',
            field=models.CharField(choices=[('Belum Disetujui', 'Belum Disetujui'), ('Tidak Disetujui', 'Tidak Disetujui'), ('Disetujui', 'Disetujui')], default='Belum Disetujui', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendaftaran_wisuda',
            name='ukuran_toga',
            field=models.CharField(choices=[('XXL', 'XXL'), ('L', 'L'), ('XL', 'XL'), ('M', 'M'), ('S', 'S')], default='L', max_length=150),
        ),
    ]
